name: Memory Profile
on: [push, pull_request]

jobs:
  memory_profile:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Set up Dependencies Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ubuntu-latest-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ubuntu-latest-gems-
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install -j8
      - run: rake compile
      - run: bundle exec rake profile_memory
